### ISSUE TITLE
Firefox Addon

### ISSUE THREAD

**Issue by MorbZ** [bvx89/magnetify#2]
Thanks for you extension. As Firefox does now support Web Extensions this extension also works on Firefox. I tested it and it works just fine without any modifications. Can you please add your Extension to the [Firefox Addon site](https://addons.mozilla.org/en-US/firefox/). If not I can offer to add it but I don't like to take away your credit for it. Cheers

**Comment by bvx89** [comment]
Wow, didn't realise people still used this extension. It's not actively maintained, as you probably can see from the git commits. A lot of the functionality is broken, since Spotify changed their API. If I were to do something with this plugin, I'd do a rewrite and fix the current problems before even considering publishing it to another addon site. I'm glad that you were able to use the plugin as-is.

To answer your question, I would prefer it if you didn't publish this to the Firefox Addon site. I hope that it's okay if you just use the plugin the way you've added it for now.

**Comment by MorbZ** [comment]
Thanks for the answer. Well as it's working fine for me and it's useful I see no reason not to use it. I respect your statement and not going to publish your version but thinking about creating one myself. Cheers
